/* tgshook_03 */
#include "hookapi.h"
#define ttPAYMENT 0
#define ttINVOKE 99
#define ttREMIT 95
#define NOPE(m) rollback(SBUF(m), __LINE__)
#define OK(m) accept(SBUF(m), __LINE__)
#define EQ(a,b) ((a)[0]==(b)[0]&&(a)[1]==(b)[1]&&(a)[2]==(b)[2]&&(a)[3]==(b)[3]&&(a)[4]==(b)[4]&&(a)[5]==(b)[5]&&(a)[6]==(b)[6]&&(a)[7]==(b)[7]&&(a)[8]==(b)[8]&&(a)[9]==(b)[9]&&(a)[10]==(b)[10]&&(a)[11]==(b)[11]&&(a)[12]==(b)[12]&&(a)[13]==(b)[13]&&(a)[14]==(b)[14]&&(a)[15]==(b)[15]&&(a)[16]==(b)[16]&&(a)[17]==(b)[17]&&(a)[18]==(b)[18]&&(a)[19]==(b)[19])
#define U8(b,i) ((uint64_t)(b)[i])
#define U64(b) ((U8(b,0)<<56)|(U8(b,1)<<48)|(U8(b,2)<<40)|(U8(b,3)<<32)|(U8(b,4)<<24)|(U8(b,5)<<16)|(U8(b,6)<<8)|U8(b,7))
#define DROP(b) (U64(b)&0x3FFFFFFFFFFFFFFFULL)
#define PUT64(m,o,v) (m)[o]=(uint8_t)((v)>>56);(m)[o+1]=(uint8_t)((v)>>48);(m)[o+2]=(uint8_t)((v)>>40);(m)[o+3]=(uint8_t)((v)>>32);(m)[o+4]=(uint8_t)((v)>>24);(m)[o+5]=(uint8_t)((v)>>16);(m)[o+6]=(uint8_t)((v)>>8);(m)[o+7]=(uint8_t)(v)
static const uint8_t META[32]={0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11,0x11};
#define LOADBAL(acc,var) do{uint8_t _k[34],_b[8];(var)=-1;if(util_keylet(SBUF(_k),KEYLET_ACCOUNT,(acc),20,0,0,0,0)==34){int64_t _s=slot_set(SBUF(_k),0);if(_s>=0&&slot_subfield(_s,sfBalance,1)>=0&&slot(SBUF(_b),1)==8)(var)=(int64_t)DROP(_b);}}while(0)
int64_t hook(uint32_t reserved){
 _g(1,1);
  uint8_t ha[20],oa[20],meta[17],cmd[8],vc[32],box[45];
   if(hook_account(SBUF(ha))!=20) NOPE("tgs: acc");
    if(otxn_field(SBUF(oa),sfAccount)!=20) NOPE("tgs: acc2");
     if(state(SBUF(meta),META,32)!=17){int i;for(i=0;GUARD(17),i<17;++i) meta[i]=0;}
      uint64_t held=U64(meta), locks=U64(meta+8);
       if(EQ(ha,oa)&&otxn_type()!=ttINVOKE){
         if(meta[16]==1&&(otxn_type()==ttREMIT||otxn_type()==ttPAYMENT)){
            meta[16]=0;
               if(state_set(SBUF(meta),META,32)!=17) NOPE("tgs: allow");
                  OK("tgs: remit");
                    }
                      uint8_t tid[32];
                        if(otxn_field(SBUF(tid),sfURITokenID)==32){
                           uint8_t f[1];
                              if(state(SBUF(f),tid,32)==1&&f[0]==1) NOPE("tgs: locked");
                                }
                                  uint8_t ids[256];
                                    int64_t n=otxn_field(SBUF(ids),sfURITokenIDs);
                                      if(n>0){
                                         int seen=0,i,off;
                                            for(i=0;GUARD(32),i<32;++i){
                                                int64_t loc=sto_subarray(ids,n,i);
                                                    if(loc<0) break;
                                                        int32_t o=(int32_t)(loc>>32), ln=(int32_t)loc;
                                                            if(o<0||ln<32||o+ln>n) NOPE("tgs: list");
                                                                uint8_t* e=ids+o; uint8_t* id=0;
                                                                    int64_t in=sto_subfield(e,ln,sfURITokenID);
                                                                        if(in>=0){
                                                                             int32_t io=(int32_t)(in>>32), il=(int32_t)in;
                                                                                  if(il==32&&io>=0&&io+32<=ln) id=e+io;
                                                                                      }
                                                                                          if(!id&&(ln==32||ln==33)) id=e+(ln-32);
                                                                                              if(!id) NOPE("tgs: list");
                                                                                                  seen=1;
                                                                                                      uint8_t f[1];
                                                                                                          if(state(SBUF(f),id,32)==1&&f[0]==1) NOPE("tgs: locked");
                                                                                                             }
                                                                                                                for(off=0;GUARD(96),off+32<=n&&off<224;++off){
                                                                                                                    uint8_t f[1];
                                                                                                                        if(state(SBUF(f),ids+off,32)==1&&f[0]==1) NOPE("tgs: locked");
                                                                                                                           }
                                                                                                                              if(!seen) NOPE("tgs: list");
                                                                                                                                }
                                                                                                                                  if(held&&(otxn_type()==ttPAYMENT||otxn_type()==ttREMIT)){
                                                                                                                                     uint8_t a[8],fee[8]; uint64_t spend=0,f=0;
                                                                                                                                        if(otxn_field(SBUF(a),sfAmount)==8) spend=DROP(a);
                                                                                                                                           if(otxn_field(SBUF(fee),sfFee)==8) f=DROP(fee);
                                                                                                                                              int64_t bal; LOADBAL(ha,bal);
                                                                                                                                                 if(bal<0||(uint64_t)bal<held+spend+f) NOPE("tgs: reserve");
                                                                                                                                                   }
                                                                                                                                                     OK("tgs: out");
                                                                                                                                                      }
                                                                                                                                                       if(otxn_type()!=ttINVOKE) OK("tgs: skip");
                                                                                                                                                        int64_t nc=otxn_param(SBUF(cmd),"CMD",3);
                                                                                                                                                         if(nc<4) NOPE("tgs: cmd");
                                                                                                                                                          int pack=cmd[0]=='P'&&cmd[1]=='A'&&cmd[2]=='C'&&cmd[3]=='K';
                                                                                                                                                           int claim=nc>=5&&cmd[0]=='C'&&cmd[1]=='L'&&cmd[2]=='A'&&cmd[3]=='I'&&cmd[4]=='M';
                                                                                                                                                            int open=cmd[0]=='O'&&cmd[1]=='P'&&cmd[2]=='E'&&cmd[3]=='N';
                                                                                                                                                             if(pack){
                                                                                                                                                               if(!EQ(ha,oa)) NOPE("tgs: owner");
                                                                                                                                                                 if(otxn_param(SBUF(vc),"VC",2)!=32) NOPE("tgs: vc");
                                                                                                                                                                   uint8_t tid[32],amt[8],exp[4];
                                                                                                                                                                     if(otxn_param(SBUF(tid),"TID",3)!=32) NOPE("tgs: tid");
                                                                                                                                                                       if(otxn_param(SBUF(amt),"AMT",3)!=8) NOPE("tgs: amt");
                                                                                                                                                                         int64_t ne=otxn_param(SBUF(exp),"EXP",3);
                                                                                                                                                                           if(ne<0) exp[0]=exp[1]=exp[2]=exp[3]=0;
                                                                                                                                                                             else if(ne!=4) NOPE("tgs: exp");
                                                                                                                                                                               int hn=0,haa=0,i;
                                                                                                                                                                                 for(i=0;GUARD(32),i<32;++i) if(tid[i]) hn=1;
                                                                                                                                                                                   for(i=0;GUARD(8),i<8;++i) if(amt[i]) haa=1;
                                                                                                                                                                                     if(!hn&&!haa) NOPE("tgs: empty");
                                                                                                                                                                                       if(haa){
                                                                                                                                                                                          int64_t bal; LOADBAL(ha,bal);
                                                                                                                                                                                             if(bal<0||(uint64_t)bal<held+U64(amt)) NOPE("tgs: not enough");
                                                                                                                                                                                               }
                                                                                                                                                                                                 if(state(SBUF(box),SBUF(vc))==45) NOPE("tgs: exists");
                                                                                                                                                                                                   for(i=0;GUARD(32),i<32;++i) box[i]=tid[i];
                                                                                                                                                                                                     for(i=0;GUARD(8),i<8;++i) box[32+i]=amt[i];
                                                                                                                                                                                                       box[40]=exp[0];box[41]=exp[1];box[42]=exp[2];box[43]=exp[3];box[44]=0;
                                                                                                                                                                                                         if(state_set(SBUF(box),SBUF(vc))!=45) NOPE("tgs: pack");
                                                                                                                                                                                                           if(haa) held+=U64(amt);
                                                                                                                                                                                                             if(hn) locks+=1;
                                                                                                                                                                                                               PUT64(meta,0,held); PUT64(meta,8,locks); meta[16]=0;
                                                                                                                                                                                                                 if(state_set(SBUF(meta),META,32)!=17) NOPE("tgs: meta");
                                                                                                                                                                                                                   if(hn){uint8_t one[1];one[0]=1;if(state_set(SBUF(one),SBUF(tid))!=1) NOPE("tgs: lock");}
                                                                                                                                                                                                                     OK("tgs: packed");
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                       if(!(claim||open)) NOPE("tgs: cmd");
                                                                                                                                                                                                                        uint8_t key[32];
                                                                                                                                                                                                                         if(claim){
                                                                                                                                                                                                                           uint8_t pk[33],sig[64],msg[52],dig[32]; int i;
                                                                                                                                                                                                                             if(otxn_param(SBUF(pk),"PK",2)!=33) NOPE("tgs: pk");
                                                                                                                                                                                                                               if(otxn_param(SBUF(sig),"SIG",3)!=64) NOPE("tgs: sig");
                                                                                                                                                                                                                                 if(util_sha512h(SBUF(key),SBUF(pk))!=32) NOPE("tgs: hash");
                                                                                                                                                                                                                                   for(i=0;GUARD(20),i<20;++i) msg[i]=oa[i];
                                                                                                                                                                                                                                     for(i=0;GUARD(32),i<32;++i) msg[20+i]=key[i];
                                                                                                                                                                                                                                       if(util_sha512h(SBUF(dig),SBUF(msg))!=32) NOPE("tgs: hash2");
                                                                                                                                                                                                                                         if(!util_verify(SBUF(dig),SBUF(sig),SBUF(pk))) NOPE("tgs: bad sig");
                                                                                                                                                                                                                                          }else{
                                                                                                                                                                                                                                            if(!EQ(ha,oa)) NOPE("tgs: owner");
                                                                                                                                                                                                                                              if(otxn_param(SBUF(vc),"VC",2)!=32) NOPE("tgs: vc");
                                                                                                                                                                                                                                                int j; for(j=0;GUARD(32),j<32;++j) key[j]=vc[j];
                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                  if(state(SBUF(box),SBUF(key))!=45) NOPE("tgs: unknown");
                                                                                                                                                                                                                                                   if(box[44]) NOPE("tgs: claimed");
                                                                                                                                                                                                                                                    uint32_t exp=((uint32_t)box[40]<<24)|((uint32_t)box[41]<<16)|((uint32_t)box[42]<<8)|box[43];
                                                                                                                                                                                                                                                     uint32_t now=(uint32_t)ledger_seq();
                                                                                                                                                                                                                                                      if(open){ if(!exp||now<=exp) NOPE("tgs: not expired"); }
                                                                                                                                                                                                                                                       else if(exp&&now>exp) NOPE("tgs: expired");
                                                                                                                                                                                                                                                        int hn=0,haa=0,i;
                                                                                                                                                                                                                                                         for(i=0;GUARD(32),i<32;++i) if(box[i]) hn=1;
                                                                                                                                                                                                                                                          for(i=0;GUARD(8),i<8;++i) if(box[32+i]) haa=1;
                                                                                                                                                                                                                                                           if(claim&&haa){
                                                                                                                                                                                                                                                             int64_t bal; LOADBAL(ha,bal);
                                                                                                                                                                                                                                                               if(bal<0||(uint64_t)bal<U64(box+32)) NOPE("tgs: not enough");
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                 if(claim&&(hn||haa)){
                                                                                                                                                                                                                                                                   uint8_t txn[320];
                                                                                                                                                                                                                                                                     for(i=0;GUARD(320),i<320;++i) txn[i]=0;
                                                                                                                                                                                                                                                                       txn[0]=0x12;txn[1]=0x00;txn[2]=0x5F;txn[3]=0x22;txn[4]=0x80;txn[8]=0x24;
                                                                                                                                                                                                                                                                         txn[13]=0x20;txn[14]=0x1A;txn[19]=0x20;txn[20]=0x1B;txn[25]=0x68;txn[26]=0x40;
                                                                                                                                                                                                                                                                           txn[34]=0x73;txn[35]=0x21;txn[69]=0x81;txn[70]=0x14;txn[91]=0x83;txn[92]=0x14;
                                                                                                                                                                                                                                                                             for(i=0;GUARD(20),i<20;++i){txn[71+i]=ha[i];txn[93+i]=oa[i];}
                                                                                                                                                                                                                                                                               uint32_t fls=now+1, lls=fls+4;
                                                                                                                                                                                                                                                                                 txn[15]=(uint8_t)(fls>>24);txn[16]=(uint8_t)(fls>>16);txn[17]=(uint8_t)(fls>>8);txn[18]=(uint8_t)fls;
                                                                                                                                                                                                                                                                                   txn[21]=(uint8_t)(lls>>24);txn[22]=(uint8_t)(lls>>16);txn[23]=(uint8_t)(lls>>8);txn[24]=(uint8_t)lls;
                                                                                                                                                                                                                                                                                     etxn_reserve(1);
                                                                                                                                                                                                                                                                                       if(etxn_details(txn+113,116)!=116) NOPE("tgs: details");
                                                                                                                                                                                                                                                                                         uint32_t o=229;
                                                                                                                                                                                                                                                                                           if(haa){
                                                                                                                                                                                                                                                                                              txn[o++]=0xF0;txn[o++]=0x5C;txn[o++]=0xE0;txn[o++]=0x5B;txn[o++]=0x61;
                                                                                                                                                                                                                                                                                                 txn[o++]=(uint8_t)(0x40|(box[32]&0x3F));
                                                                                                                                                                                                                                                                                                    for(i=1;GUARD(7),i<8;++i) txn[o++]=box[32+i];
                                                                                                                                                                                                                                                                                                       txn[o++]=0xE1;txn[o++]=0xF1;
                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                           if(hn){
                                                                                                                                                                                                                                                                                                              txn[o++]=0x00;txn[o++]=0x13;txn[o++]=0x63;txn[o++]=0x20;
                                                                                                                                                                                                                                                                                                                 for(i=0;GUARD(32),i<32;++i) txn[o++]=box[i];
                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                     int64_t fee=etxn_fee_base(txn,o);
                                                                                                                                                                                                                                                                                                                       if(fee<0) NOPE("tgs: fee");
                                                                                                                                                                                                                                                                                                                         uint64_t fv=(uint64_t)fee;
                                                                                                                                                                                                                                                                                                                           txn[26]=(uint8_t)(0x40|((fv>>56)&0x3F));
                                                                                                                                                                                                                                                                                                                             txn[27]=(uint8_t)(fv>>48);txn[28]=(uint8_t)(fv>>40);txn[29]=(uint8_t)(fv>>32);
                                                                                                                                                                                                                                                                                                                               txn[30]=(uint8_t)(fv>>24);txn[31]=(uint8_t)(fv>>16);txn[32]=(uint8_t)(fv>>8);txn[33]=(uint8_t)fv;
                                                                                                                                                                                                                                                                                                                                 meta[16]=1;
                                                                                                                                                                                                                                                                                                                                   if(state_set(SBUF(meta),META,32)!=17) NOPE("tgs: allow");
                                                                                                                                                                                                                                                                                                                                     uint8_t hx[32];
                                                                                                                                                                                                                                                                                                                                       if(emit(SBUF(hx),txn,o)!=32) NOPE("tgs: emit");
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                         box[44]=1;
                                                                                                                                                                                                                                                                                                                                          if(state_set(SBUF(box),SBUF(key))!=45) NOPE("tgs: mark");
                                                                                                                                                                                                                                                                                                                                           if(haa&&held>=U64(box+32)) held-=U64(box+32);
                                                                                                                                                                                                                                                                                                                                            if(hn&&locks) locks-=1;
                                                                                                                                                                                                                                                                                                                                             PUT64(meta,0,held); PUT64(meta,8,locks);
                                                                                                                                                                                                                                                                                                                                              if(state_set(SBUF(meta),META,32)!=17) NOPE("tgs: meta");
                                                                                                                                                                                                                                                                                                                                               if(hn){uint8_t z[1];z[0]=0;if(state_set(SBUF(z),box,32)!=1) NOPE("tgs: unlock");}
                                                                                                                                                                                                                                                                                                                                                OK(open?"tgs: opened":"tgs: claimed");
                                                                                                                                                                                                                                                                                                                                                }